language: objective-c
xcode_sdk: iphonesimulator
before_install:
    - brew update
    - cd STTweetLabelExample
script: xcodebuild -project STTweetLabelExample.xcodeproj -scheme STTweetLabelExample -sdk iphonesimulator test
